# -*- coding: utf-8 -*-
"""ifelse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fWQ5xUQGq8AE-BwcwTinroGX-txoWoP
"""



#This program prompts the user to input their name. If the name entered is "Alice", it prints "Hi, Alice!". Otherwise, it prints "How are you, " followed by the name entered by the user.

name = input("Enter your name: ")

if name == "Alice":
    print("Hi, Alice!")
else:
    print("How are you, " + name + "?")

#This program  first checks if the name is "Alice", then checks if it's "John". If the name is "Alice", it prints "Hi". If the name is "John", it says "What's up". Otherwise, it prints "Nice to meet you" followed by the input name:
fname = input("Enter your First name: ")

if fname == "Alice":
    print("Hi, Alice!")
elif fname == "John":
    print("What's up, John?")
else:
    print("Nice to meet you,  "+ fname +"" )